import esbuild from "esbuild";
import process from "process";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const projectDir = path.dirname(fileURLToPath(import.meta.url));
const prod = process.argv[2] === "production";

// Output goes straight into the Obsidian vault plugin folder so it can be
// reloaded without a manual copy. Override with OBSIDIAN_PLUGIN_DIR.
const VAULT_PLUGIN_DIR =
  process.env.OBSIDIAN_PLUGIN_DIR ||
  "C:\\Users\\lenovo\\Documents\\Obsidian Vault\\.obsidian\\plugins\\short-phrase-cards";

fs.mkdirSync(VAULT_PLUGIN_DIR, { recursive: true });

for (const name of ["manifest.json", "styles.css"]) {
  fs.copyFileSync(
    path.join(projectDir, name),
    path.join(VAULT_PLUGIN_DIR, name)
  );
}

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: [path.join(projectDir, "src/main.ts")],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/*",
    "@lezer/*",
    "@codemirror/state",
    "@codemirror/view",
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: path.join(VAULT_PLUGIN_DIR, "main.js"),
});

if (prod) {
  await context.rebuild();
  await context.dispose();
  process.exit(0);
} else {
  await context.watch();
}
